### ISSUE TITLE
Stable DART versions?

### ISSUE THREAD

**Issue by acxz** [dartsim/dartsim.github.io#12]
I was looking at the [Dartsim Download Page](http://dartsim.github.io/download.html) and it seems that the latest stable version is Dart 6.1.2. The [API Documentation Page](http://dartsim.github.io/download.html) mentions that version 7.0.0 and 6.4.0 are unstable and the rest of the versions statuses are not listed. When I install Dart from the Ubuntu PPA, the release version is 6.6.1. Basically it seems like the website is outdated with regards to the github repo and releases. It would be great if the version statuses can be updated on the dartsim.github.io page.

I also have a question. Is the Dart version on the Ubuntu PPA considered the latest stable version? Because based on the above information I have noticed above, the latest mentioned stable version is 6.1.2 which is outdated. If possible I would like confirmation that the Ubuntu PPA released version is stable so that I can use it on physical hardware with more confidence than another Dart version.

Oh one more question. Which API documentation version should I use with 6.6? Or do these also need to be updated?

**Comment by jslee02** [comment]
I believe this is resolved. Feel free to reopen if you have further concerns. Thanks!

**Comment by acxz** [comment]
Thanks so much!!!
