### ISSUE TITLE
Help Forum

### ISSUE THREAD

**Issue by acxz** [dartsim/dartsim.github.io#15]
I think it would be a great idea to have a site with a forum related to DART. DART users can ask for help on implementation problems, since submitting issues on the `dart` repo for implementation seems inappropriate. While the tutorials are helpful, there can be some disconnect between what a user wants DART to do versus implementing the correct API functionality in their code.

For example, I am trying to write collision code that obtains the shortest distance between all pairs of SkeletonPtr's in the world. However, I am struggling to call the right DART methods to achieve this. Having a forum would allow others to comment on and fix my issue.

I was wondering if this would be of interest or a future plan for the project.

**Comment by mxgrey** [comment]
I completely agree that a forum would be a more appropriate venue for users to ask questions than Github issues. That said, I don't know that there's currently enough traffic of user questions to justify opening forum infrastructure. (But then again, maybe having a forum would motivate more people to ask questions?)

> I am trying to write collision code that obtains the shortest distance between all pairs of SkeletonPtr's in the world

For this I'm afraid you might be a little bit out of luck. The collision detectors that DART uses under the hood don't generally support calculating the distances between geometries that aren't in collision.

If you're using convex shapes then you could try out [this code](https://github.com/mzucker/ccdwrapper) that wraps `libccd` to compute minimum distances. It's not integrated with DART, but it uses `Eigen`, which is also what's used by DART, so you could easily use DART to update the transforms for the `TransformedConvex` class in that wrapper.

**Comment by acxz** [comment]
First off, thanks for helping me out on my problem! I'll take a look into it.

I believe what you said for the forum is true, however, having a place for users would also encourage new users to join the DART community. I am not exactly sure how difficult it would be to incorporate a forum in the current website, but if it is not too hard then it would be great for the community. Maybe an already existing tool can be used?

As a temporary solution, users can be directed to post issues on the Github Page with the appropriate label, such as "implementation". This information should be on the DART website to increase visibility.

**Comment by jslee02** [comment]
I thought about experimentally running a forum, but couldn't find a good non-commercial web-hosted one. Please let me know if anyone have good suggestions.

Regarding distance computation: @mxgrey is correct that not all the collision detectors support it but FCL does! If you use FCL collision detector, which is the default, you should be able to get the minimum distances either of the minimum distance within a geometry groups (CollisionGroup) or the minimum distance between two geometry groups. Please take a look at [this API](https://github.com/dartsim/dart/blob/master/dart/collision/CollisionDetector.hpp#L128-L157).

**Comment by acxz** [comment]
Ahh, I see. I think that is just what I wanted.

I looked around for some forums and I found [FluxBB](https://fluxbb.org/), an open-source and simple platform. I looked into what ROS and Gazebo used for their forums, but [AskRobot](https://askbot.com/) is commercial.

**Comment by jslee02** [comment]
We've created [DART forum](https://dartsim.discourse.group/) thanks to [Discourse](https://www.discourse.org/)! You can also find the link from the top navigation bar of the [DART website](http://dartsim.github.io/index.html). I hope this helps the DART user community. @acxz Thanks for the suggestions though!

**Comment by acxz** [comment]
This makes me very happy!
