### ISSUE TITLE
DART installation for other operating systems

### ISSUE THREAD

**Issue by acxz** [dartsim/dartsim.github.io#16]
In addition to the operating systems currently supported (Ubuntu, Mac, Windows), community maintainers have also created packages and ports for other OSs, like [ArchLinux](https://aur.archlinux.org/packages/libdart/) and [FreeBSD](https://www.freebsd.org/cgi/ports.cgi?query=dartsim&stype=all). From what I understand a Debian package is also on the horizon.

In lieu of this, I think the Installation page should be expanded to include these options to target an even larger user base.

Maybe something like:

Installation
- Linux
  - Ubuntu
  - Debian
  - Archlinux
- BSD
  - FreeBSD
- Mac
- Windows

**Comment by jslee02** [comment]
This sounds good to me. I'm not familiar with the OSs so it'd be awesome if we have volunteers. I've created an simple template pages for it: https://github.com/dartsim/dartsim.github.io/pull/17.

**Comment by acxz** [comment]
Just opened a  PR [#18](https://github.com/dartsim/dartsim.github.io/pull/18) for the archlinux instructions.

**Comment by acxz** [comment]
I would like to ping @yurivict for help on the FreeBSD installation page, based on yurivict's contribution to the FreeBSD port.

**Comment by yurivict** [comment]
In order to install it on FreeBSD, run this command: ```pkg install dartsim```.

**Comment by acxz** [comment]
With PRs [#17](https://github.com/dartsim/dartsim.github.io/pull/17), [#18](https://github.com/dartsim/dartsim.github.io/pull/18), and [#19](https://github.com/dartsim/dartsim.github.io/pull/19) adding instructions for installation, I'll go ahead and close this issue.

Note foreseeable changes include getting the Windows build working and updating installation instructions if `pagmo` becomes packaged.
