### ISSUE TITLE
broken link to "OpenSceneGraph based examples" page

### ISSUE THREAD

**Issue by olzhas** [dartsim/dartsim.github.io#6]
on page http://dartsim.github.io/install_dart_on_ubuntu.html#install-optional-dependencies
the link to "OpenSceneGraph based examples" 
(points to http://dartsim.github.io/mydoc_gallery.html#openscenegraph-based-examples)

**Comment by jslee02** [comment]
Fixed by https://github.com/dartsim/dartsim.github.io/commit/60ebf0158379a0ae0d59562de2308d9487615a43. Thanks!
